version: '3.1'

services:
  postgresql:
    image: postgres:latest
    container_name: pg
    ports:
      - 5432:5432
    volumes: 
      - ./pg/data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=test
